### PR TITLE
test(e2e): fix indentation for dump logs

### PR DESCRIPTION
**Pull request by charliedmcb**
Fixes # 

**Description**
@tallaxes noticed that the log dump on failure was not working.

Looking into it I noticed that the action was not indented correctly. This PR fixes the indentation, and the issues with the log dump.

**How was this change tested?**
I ran the E2E pipeline with a guaranteed failure [in drift] with the log dumps current status in main, which caused it to fail:
https://github.com/Azure/karpenter/actions/runs/6829122309/job/18574667354
Then I ran it with the guaranteed failure [in drift] with the log dump indentation fixed:
https://github.com/Azure/karpenter/actions/runs/6829114912
The fixed indentation executed correctly.
*

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [x] No

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by tallaxes — APPROVED** [review]

**Comment by charliedmcb** [comment]
Completing without getting the E2E tests to pass as this change should not non-impactful on the actual suites, and verified the fix to the flow works as desired.

**Pull request merged**
