### PR TITLE
fix: properly closing tcp connections in sdk to fix timeout errors

### PR DESCRIPTION
**Pull request by Bryce-Soghigian**
**Description**
We will occasionally get an error like:
```
{"name":"sm-general-purpose-vdnt7"},"namespa
ce":"","name":"sm-general-purpose-vdnt7","reconcileID":"11d07c7c-6c56-4d0a-b49f-50393126d7a9","error":"launching nodeclaim, creating instanc
e, Get \"https://management.azure.com/subscriptions/(redacted)/providers/Microsoft.Network/locations/eastus/operat
ions/(redacted)?api-version=2022-01-01\": dial tcp 20.62.130.212:443: i/o timeout"}
```
This is caused by an issue in the go std library [Ref](https://github.com/golang/go/issues/59690)
When a TCP connection is dropped, there is a bug in the http2 implementation in go that misses to mark the connection as failed. as a result, the connection stays in the pool, and the calls using that connection hit a context deadline.
The connection can stay in the pool fur up to 17 min (with default linux kernel settings).

This PR updates our http client to share its configuration with the AKS Recommended Default middleware provided in the azure-sdk-for-go-extensions project that fixes the pool getting filled up. 

**How was this change tested?**
- unit tests in the azure-sdk-for-go-extensions 
- proven to fix issue in prod via various aks services that have adopted these client options

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [x] No

**Release Note**

```release-note
Fixing TCP Timeout Errors from stale connections in the pool 
```

### CODE REVIEW

**Review by Bryce-Soghigian — COMMENTED** [review]
/test

**Comment by Bryce-Soghigian** [comment]
See PR Adding this update to the middleware: https://github.com/Azure/azure-sdk-for-go-extensions/pull/29

**Comment by Bryce-Soghigian** [comment]
Screenshot 2023-11-22 at 8 46 23 PM
Coveralls is failing because i removed code in a file with 100% coverage so it lowered overall percentage

**Review by Bryce-Soghigian — COMMENTED** [review]
/test

**Review by tallaxes — APPROVED** [review]

**Pull request merged**
