### PR TITLE
chore: remove all references to linking

### PR DESCRIPTION
**Pull request by rakechill**
**Description**
With the API update from machine -> nodeclaim, the karpenter provider removed the linking controller completely.

**How was this change tested?**
* gc tests still behaving correctly
* e2e suites (running in the PR)
* scale up/scale down works correctly

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [X] No

**Release Note**

```release-note

```

### CODE REVIEW

**Review by rakechill — COMMENTED** [review]
/test

**Comment by Bryce-Soghigian** [comment]
https://github.com/kubernetes-sigs/karpenter/blob/main/pkg/controllers/nodeclaim/lifecycle/launch.go#L59 looks like we dont support launchign nodeclaims with linking anymore in karpenter core so I am all for this change. 


Do you know what version of karpneter core it was removed? Was it v0.33 or v0.32?

**Comment by rakechill** [comment]
> https://github.com/kubernetes-sigs/karpenter/blob/main/pkg/controllers/nodeclaim/lifecycle/launch.go#L59 looks like we dont support launchign nodeclaims with linking anymore in karpenter core so I am all for this change.
> 
> Do you know what version of karpenter core it was removed? Was it v0.33 or v0.32?

@Bryce-Soghigian I'm looping back to this now + rebased from main. I feel fairly confident we don't need it. However, I still can't find the exact reason *why* the karpenter aws provider decided to remove this. They [claimed](https://github.com/aws/karpenter-provider-aws/pull/5009) it had to do w/ removing `machineutils` in karpenter-core, but I'm not entirely clear why that would have made linking unnecessary.

The two relevant PRs seem to be:
* https://github.com/kubernetes-sigs/karpenter/pull/658
* https://github.com/kubernetes-sigs/karpenter/pull/648

And they were both in [v0.33.0](https://github.com/kubernetes-sigs/karpenter/releases/tag/v0.33.0)

**Review by rakechill — COMMENTED** [review]
/test

**Comment by Bryce-Soghigian** [comment]
> > https://github.com/kubernetes-sigs/karpenter/blob/main/pkg/controllers/nodeclaim/lifecycle/launch.go#L59 looks like we dont support launchign nodeclaims with linking anymore in karpenter core so I am all for this change.
> > Do you know what version of karpenter core it was removed? Was it v0.33 or v0.32?
> 
> @Bryce-Soghigian I'm looping back to this now + rebased from main. I feel fairly confident we don't need it. However, I still can't find the exact reason _why_ the karpenter aws provider decided to remove this. They [claimed](https://github.com/aws/karpenter-provider-aws/pull/5009) it had to do w/ removing `machineutils` in karpenter-core, but I'm not entirely clear why that would have made linking unnecessary.
> 
> The two relevant PRs seem to be:
> 
> * [chore: remove v1alpha5 utils kubernetes-sigs/karpenter#658](https://github.com/kubernetes-sigs/karpenter/pull/658)
> * [chore: remove v1alpha5 from lifecycle/consistency/garbage collection kubernetes-sigs/karpenter#648](https://github.com/kubernetes-sigs/karpenter/pull/648)
> 
> And they were both in [v0.33.0](https://github.com/kubernetes-sigs/karpenter/releases/tag/v0.33.0)

@jackfrancis  can you provide any insight here before we merge this?

**Comment by tallaxes** [comment]
The way I see it, linking is/was about Karpenter adopting instances that it did not provision, potentially useful for migrating existing clusters to Karpenter (or maybe incompatible Karpenter versions). Removing this means either that these scenarios are considered less important, or they (possibly in some cases) did not actually work well, or the implementation itself was lacking (e.g. the separation between cloud provider and core responsibilities was not clean enough) - and could be revisited in the future. @jonathan-innis, any insight on this?

In any case, lets remove it and revisit later, if needed, together with required core changes.

**Review by tallaxes — APPROVED** [review]

**Comment by jonathan-innis** [comment]
> the karpenter provider removed the linking controller completely

**Comment by jonathan-innis** [comment]
I think if we want to talk about Karpenter re-owning existing nodes, we can start a design discussion about this or open an issue on `kubernetes-sigs/karpenter` to talk about the ramifications of doing this, but the stance up to this point has been to just ask users to deprovision old instances and let Karpenter launch new ones, rather than having to reason about the edge behavior that might happen if we tag and re-own an instance that was launched by a different system.

**Pull request merged**
