### PR TITLE
test(e2e): remove wait on gatekeeper

### PR DESCRIPTION
**Pull request by charliedmcb**
Fixes # 

**Description**
This wait was in place when we had a taint added that stopped any new pods from provisioning on the system nodes. 

However, we switched to `CriticalAddonsOnly` which the gatekeeper pods have a Toleration for:
image

So should be able to remove this and speed up the cluster creation process.

**How was this change tested?**
Ran the e2e pipeline 5 times and didn't spot anything obviously an issue from gatekeeper.
*

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [x] No

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by tallaxes — APPROVED** [review]

**Pull request merged**
