### PR TITLE
test(e2e): add in grouping for e2e logs

### PR DESCRIPTION
**Pull request by charliedmcb**
Fixes # 

**Description**
Allows for collapsing of the controller logs for an E2E run:
image

This is particularly nice when multiple tests are run within the same suite.

**How was this change tested?**
Nothing additional
*

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [x] No

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by tallaxes — APPROVED** [review]

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by charliedmcb — COMMENTED** [review]
/test

**Pull request merged**
